import {renderPage,drawPhoto,paginate,wrapText,PW,PH} from '../layout.js';
const results=document.querySelector('#results');const messages=[];
function check(ok,name){messages.push(`${ok?'PASS':'FAIL'} ${name}`);results.textContent=messages.join('\n');if(!ok)throw Error(name);}
try{
  const fonts=await document.fonts.load('46px Diary','한글');await document.fonts.ready;check(fonts.length>0,'한글 웹폰트 로딩');
  const image=document.createElement('canvas');image.width=1200;image.height=800;const ic=image.getContext('2d');ic.fillStyle='#73a4b4';ic.fillRect(0,0,1200,800);ic.fillStyle='#ddb47e';ic.fillRect(0,0,600,400);ic.fillStyle='#355344';ic.fillRect(600,400,600,400);
  const cropCanvas=document.createElement('canvas');cropCanvas.width=PW;cropCanvas.height=PH;const cc=cropCanvas.getContext('2d');const output=document.querySelector('#result');
  for(const zoom of [1,1.8,4])for(const [x,y] of [[.5,.5],[.25,.75],[.8,.2]]){const crop={zoom,x,y};drawPhoto(cc,image,crop);renderPage(output,{top:930,lines:['오늘도 소중한 하루.','한글 가각간 가나다라 힣'],photo:true},0,1,'2026-09-21',image,crop);const a=cc.getImageData(0,0,PW,PH).data,b=output.getContext('2d').getImageData(96,266,PW,PH).data;check(a.every((value,i)=>value===b[i]),`crop 픽셀 일치 (zoom ${zoom}, center ${x}/${y})`);}
  const blob=await new Promise(resolve=>output.toBlob(resolve,'image/png'));const png=await createImageBitmap(blob);check(png.width===1080&&png.height===1920,'PNG 1080 × 1920');const decoded=document.createElement('canvas');decoded.width=1080;decoded.height=1920;decoded.getContext('2d').drawImage(png,0,0);const raw=output.getContext('2d').getImageData(0,0,1080,1920).data,copy=decoded.getContext('2d').getImageData(0,0,1080,1920).data;check(raw.every((v,i)=>v===copy[i]),'미리보기와 PNG 디코딩 픽셀 완전 일치');png.close();
  for(const align of ['left','justify','right']){renderPage(output,{top:300,lines:[{text:'한글 정렬을 확인하는 충분히 긴 본문입니다.',justify:true},{text:'문단 마지막 줄',justify:false}],photo:false},0,1,'2026-09-21',null,{zoom:1,x:.5,y:.5},{memo:'☀️ 엄청 더움',align,bodyFont:'Diary'});check(output.width===1080&&output.height===1920,`${align} 정렬과 날짜 옆 메모 렌더링`);}
  renderPage(output,{top:300,lines:[{text:'명조 장평과 자간 확인',justify:false}],photo:false},0,1,'2026-09-21',null,{zoom:1,x:.5,y:.5},{memo:'🎂 엄마 생일 ☀️',align:'left',bodyFont:'Batang,serif',scaleX:.95,letterSpacing:-46*.03,condensed:true});check(output.width===1080&&output.height===1920,'명조 95% 장평·-3% 자간과 이모지 폴백 렌더링');
  for(const [paperColor,rgb] of [['#fffefb',[255,254,251]],['#fbfdff',[251,253,255]],['#fffafb',[255,250,251]],['#fbfef9',[251,254,249]],['#fdfdfd',[253,253,253]]]){renderPage(output,{top:300,lines:[],photo:false},0,1,'2026-09-21',null,{zoom:1,x:.5,y:.5},{paperColor});const pixel=[...output.getContext('2d').getImageData(0,0,1,1).data].slice(0,3);check(pixel.every((v,i)=>v===rgb[i]),`${paperColor} 종이색 미리보기·PNG 렌더러 적용`);}
  for(const [photoFormat,height] of [['classic',600],['square',888],['full',1480]]){const formatCrop={zoom:1.4,x:.4,y:.6};renderPage(output,{top:1810,lines:[],photo:true},0,1,'2026-09-21',image,formatCrop,{photoFormat});const expected=document.createElement('canvas');expected.width=PW;expected.height=height;drawPhoto(expected.getContext('2d'),image,formatCrop,0,0,PW,height);const actual=output.getContext('2d').getImageData(96,266,PW,height).data;check(expected.getContext('2d').getImageData(0,0,PW,height).data.every((v,i)=>v===actual[i]),`${photoFormat} 사진 비율 crop 픽셀 일치`);}
  const text='오늘은 한글 줄바꿈을 확인하는 날입니다. 가족과 함께 걸었고, 조용한 오후를 보냈습니다.\n\n'.repeat(50);const ctx=output.getContext('2d');ctx.font='46px Diary';const lines=wrapText(text,s=>ctx.measureText(s).width);const pages=paginate(lines,true);check(pages.length>2,'긴 한글 자동 페이지 분할');check(pages.flatMap(p=>p.lines).join('')===text.replaceAll('\n',''),'페이지 분할 후 글자 누락 없음');check(lines.every(s=>ctx.measureText(s).width<=PW),'모든 줄이 본문 영역 안에 배치');check(pages.slice(1).every(p=>!p.photo&&p.top===300),'2페이지부터 사진 생략');
  results.textContent+='\n완료';
}catch(error){results.textContent+='\nERROR '+error.message;}
