const frame=document.querySelector('iframe');
frame.addEventListener('load',async()=>{
  const d=frame.contentDocument,w=frame.contentWindow;await d.fonts.load('46px Diary','한글');await d.fonts.ready;
  d.querySelector('#body').value='오늘은 천천히 걸었다.\n\n작고 소중한 순간을 기억하고 싶다.';d.querySelector('#body').dispatchEvent(new w.Event('input',{bubbles:true}));
  const source=d.createElement('canvas');source.width=400;source.height=700;const sourceContext=source.getContext('2d');sourceContext.fillStyle='#6b9fe6';sourceContext.fillRect(0,0,400,350);sourceContext.fillStyle='#76bd78';sourceContext.fillRect(0,350,400,350);const blob=await new Promise(resolve=>source.toBlob(resolve,'image/png'));const transfer=new w.DataTransfer();transfer.items.add(new w.File([blob],'mobile-test.png',{type:'image/png'}));const photo=d.querySelector('#photo');photo.files=transfer.files;photo.dispatchEvent(new w.Event('change',{bubbles:true}));
  await new Promise(r=>setTimeout(r,250));const crop=d.querySelector('#crop'),cropContext=crop.getContext('2d'),pixel=(x,y)=>[...cropContext.getImageData(x,y,1,1).data].slice(0,3);const beforeTop=pixel(10,10),beforeBottom=pixel(10,crop.height-10);d.querySelector('#rotateRight').click();await new Promise(r=>setTimeout(r,100));const afterLeft=pixel(10,crop.height/2),afterRight=pixel(crop.width-10,crop.height/2);const rotated=beforeTop[2]>beforeTop[1]&&beforeBottom[1]>beforeBottom[2]&&afterLeft[1]>afterLeft[2]&&afterRight[2]>afterRight[1];const format=d.querySelector('#photoFormat');format.value='full';format.dispatchEvent(new w.Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,100));
  const results=[];results.push(`${d.querySelectorAll('input[name="paperColor"]').length===5?'PASS':'FAIL'} 종이색 선택지 5개`);results.push(`${rotated?'PASS':'FAIL'} 오른쪽 90도 회전 픽셀 방향`);results.push(`${!d.querySelector('#cropPanel').hidden&&d.querySelector('#crop').height===1480?'PASS':'FAIL'} 넓은 사진 crop과 회전 UI 표시`);for(const width of [320,390,430]){frame.style.width=width+'px';await new Promise(r=>requestAnimationFrame(r));const controls=[...d.querySelectorAll('input,select,button,textarea,canvas,.paper')];const inside=controls.every(el=>{const r=el.getBoundingClientRect();return r.left>=-1&&r.right<=width+1;});const stacked=width>430||d.querySelector('.writing-settings').getBoundingClientRect().height>90;results.push(`${d.documentElement.scrollWidth<=width?'PASS':'FAIL'} ${width}px 페이지 가로 넘침 없음 (${d.documentElement.scrollWidth}px)`);results.push(`${inside?'PASS':'FAIL'} ${width}px 입력·사진·미리보기 잘림 없음`);results.push(`${stacked?'PASS':'FAIL'} ${width}px 설정 UI 세로 배치`);}
  frame.style.width='390px';document.querySelector('#result').textContent=results.join('\n');
});
